[deploy]
bucket = 'cfn-artifacts-cruddur'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.pl'
EnvBackendUrl = 'https://api.cruddur.pl'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1PZ7ZD5UMVNO0'