name: Sync-Prod-Frontend

env:
  CI: false
  SYNC_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SYNC_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AUTO_APPROVE: false
  AWS_DEFAULT_REGION: us-east-1
  BUILD_DIR: ${{ github.workspace }}/build
  CLOUDFRONT_DISTRUBTION_ID: E8FPS47AJCWON
  OUTPUT_CHANGESET_PATH: ${{ github.workspace }}/tmp/sync-changeset.json
  S3_BUCKET: cruddur.pl


on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:
    name: Statically Build Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
             cd ${{ github.workspace }}/frontend-react-js
             npm i
             npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: ${{ github.workspace }}/frontend-react-js/build
  deploy:
    name: Sync Static Build to S3 Bucket
    runs-on: ubuntu-latest
    needs: build
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::928597128531:role/CrdSyncRole-Role-16WHWVDVU2CUT
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: | 
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/frontend-react-js
          echo yes | bundle exec rake sync